### ISSUE TITLE
Full version of MS academic dataset?

### ISSUE THREAD

**Issue by leowyy** [klicperajo/ppnp#1]
Hi, thank you for making your code available on GitHub.

I've noticed that the MS academic dataset in this repo has only 5,116 nodes. On the other hand, the dataset mentioned in the paper has 18,333 nodes. If possible, may I know where I can find the full version of this dataset? Thank you!

**Comment by gasteigerjo** [comment]
I've accidentally uploaded the wrong dataset. It should be the right one now. Thank you for pointing this out!
