### ISSUE TITLE
How to use this project for my own data

### ISSUE THREAD

**Issue by 2danlin** [klicperajo/ppnp#11]
Besides, could you please tell me how to use this project for my own data?
Specifically, what is the format of the data provided by you?
Thank you so much.

**Comment by gasteigerjo** [comment]
The models as used in [simple_example_pytorch.ipynb](https://github.com/klicperajo/ppnp/blob/master/simple_example_pytorch.ipynb) use a [SparseGraph](https://github.com/klicperajo/ppnp/blob/f4424541ecf0f12a308af168644d3b983ba8d6ae/ppnp/data/sparsegraph.py#L14). This class is just a simple Python class wrapping NumPy matrices or sparse SciPy CSR matrices. The class description explains how to use this with your own data.

Alternatively, you can use the [networkx_to_sparsegraph](https://github.com/klicperajo/ppnp/blob/f4424541ecf0f12a308af168644d3b983ba8d6ae/ppnp/data/io.py#L61) function to convert a NetworkX graph to a SparseGraph.
