### ISSUE TITLE
A new feature need Python>=3.10

### ISSUE THREAD

**Issue by BravoFr0st** [klicperajo/ppnp#17]
Hi! 
I'm using PPNP method to implement my class project. It seems that https://github.com/gasteigerjo/ppnp/commit/932679e4fa3fbda3c49177008e0823b6bd457ecd#diff-9448c7e066e7f923c452dba201314a7fb19ee57551e66279bd86396b43928ce8R9
introduce a feature supported by Python >=3.10. 
Dose it matter if I change it back to the older "calc_A_hat"?
Thanks!

**Comment by gasteigerjo** [comment]
Not sure why you wouldn't just use Python 3.10, but I've just pushed a change that uses the old `Union` syntax to be more backwards compatible. So this should work now.

**Comment by BravoFr0st** [comment]
Thanks!
