### ISSUE TITLE
About comparing to Ying. 2018

### ISSUE THREAD

**Issue by yzthz** [klicperajo/ppnp#2]
Hi,

Thanks for the nice work! wonder if you could give a short description of the difference between this work's message passing and that of Ying. 2018, Graph Convolutional Neural Networks for Web-Scale Recommender Systems?
Both use (approximate) personalized page rank for message passing. Is there any procedural difference?

Thanks!
D

**Comment by gasteigerjo** [comment]
Thank you for the interest in our work! First of all, Ying's PinSage model does _not_ use personalized PageRank. PinSage uses (explicit) random walks, which approximate regular PageRank in the limit of infinite length. It therefore exhibits all the problems described in our paper.

Additionally, PPNP is not a regular message passing neural network (MPNN). Instead, PPNP disentangles prediction and propagation by first using a neural network for prediction and then propagating these predictions using PPR.
