### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by tonyandsunny** [klicperajo/ppnp#3]
Hi! Are these datasets directed graph before the normalization?

**Comment by gasteigerjo** [comment]
The raw data of `Citeseer` and `Cora-ML` are directed, while `PubMed` and `MS Academic` are undirected in the repository.

When training any model we first preprocess the data and make the graphs undirected.

**Comment by tonyandsunny** [comment]
Thanks a lot !
Where did you download this dataset? Could you pride this link? And Could you publish the directed dataset of PubMed and Academic?

**Comment by gasteigerjo** [comment]
I don't have directed versions of these datasets. You can download the datasets from the appropriate folder in this repository, i.e. [here](https://github.com/klicperajo/ppnp/tree/master/ppnp/data).

For the original data sources, please see the references in our paper.
