### ISSUE TITLE
ValueError of graph.standarlize

### ISSUE THREAD

**Issue by jtxtina** [klicperajo/ppnp#4]
<img width="1130" alt="Screenshot 2019-10-27 at 23 49 44" src="https://user-images.githubusercontent.com/44399033/67637334-85be1580-f914-11e9-9ac1-de700d73ed28.png">
So I encountered this "missing match of shape" error. And I failed to find fixes for such bugs online. Could you tell me how to solve it? Thank you so much!

**Comment by gasteigerjo** [comment]
This is a bug in SciPy that got introduced in version 1.3.0 and will be fixed in 1.4.0. https://github.com/scipy/scipy/issues/10910

I've implemented a workaround in 9684478.
